language: java
jdk:
  - openjdk10
install: 
  - sh -c 'cd jOOX && mvn install -DskipTests=true'
  - sh -c 'cd jOOX-java-6 && mvn install -DskipTests=true'
script: 
  - sh -c 'cd jOOX && mvn test'
  - sh -c 'cd jOOX-java-6 && mvn test'

cache:
  directories:
  - $HOME/.m2
